services:
  - type: web
    name: mujacm-backend
    env: node
    branch: main
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars: []
